version: '3.1'
services:

  client_mobile:
    restart: always
    build:
      context: ./ClientMobile
      dockerfile: Dockerfile
    volumes:
      - 'myshare:/shared'

  client_web:
    restart: always
    build:
      context: ./DjangoWeb
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    expose:
      - "8081"
    networks:
      - client-server
    volumes:
      - 'myshare:/shared'

  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - client-server

networks:
  client-server:
    driver: bridge

volumes:
  myshare:
    driver: local 