version: '3.1'
services:
  server:
    restart: always
    build:
      context: ./ClientWeb
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
    expose:
      - "8080"
    networks:
      - client-server

  
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dashboard
      MONGO_INITDB_ROOT_PASSWORD: pasdami
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    networks: 
      - server-db

  api:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - server-db
      - client-server

networks:
  client-server:
    driver: bridge
  server-db:
    driver: bridge
